%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/yk/桌面/rgbd_dataset_freiburg1_xyz

# camera intrinsics
# fr1 相机的内参
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

# fr2
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7

#深度相机的尺度因子：尺度因子是深度相机特有的，就是对测量的深度值除以这个尺度因子就得到实际的深度值，以米为单位
camera.depth_scale: 20000

# VO Parameters
number_of_features: 500  #提取特征点的个数
scale_factor: 1.2        #图像金字塔的尺度因子
level_pyramid: 4         #图像金字塔的层数
match_ratio: 2.0         #特征点匹配完了后，需要筛选。系统中筛选的方式是：根据最小距离，对matches数组进行刷选，只有小于最小距离一定倍率（match_ratio）或者小于30的才能push_back进数组。
max_num_lost: 10         #最大连续丢失次数
min_inliers: 30          #系统使用这个参数的地方是 ：  判断pnp求解后内点的个数是否小于这个个数。 如果小于的话，判断当前计算的位姿不好
keyframe_rotation: 0.1     #两个关键帧的最小旋转角度
keyframe_translation: 0.1  #两个关键帧的最小平移
map_point_erase_ratio: 0.1  #地图点剔除的比例. 定义 匹配率=用匹配次数/可见次数 如果匹配率小于这个map_point_erase_ratio_则从地图中删除该点
